server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallet/**
          filters:
            - AuthenticationFilter

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/api/shop/**
          filters:
            - AuthenticationFilter

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"