server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/api/wallet/**
        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/api/shop/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**
