server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_wallet?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Omarm@138
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
jwt:
  secret: change-this-secret-key-to-a-long-random-production-secret-123456789
